In [7]:
import tensorflow as tf

A tensor is an N-dimensional array of data

Dimension = Rank

In [8]:
tf.constant(3) # Rank 0, aka Scalar, shape: ()
tf.constant([3, 5, 7]) # Rank 1, Vector (3,)
tf.constant([[3, 5, 7], [4, 6, 8]]) # Rank 2, MAtrix (2, 3)
tf.constant([[[3, 5, 7], [4, 6, 8]], # Rank 3 3D Tensor (2,2,3)
            [[1, 2, 3], [4, 5, 6]]])


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[3, 5, 7],
        [4, 6, 8]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [10]:
# Can stack variables together to create nD tensors
x1 = tf.constant([2,3,4]) # (3,)
x2 = tf.stack([x1, x1]) # (2,3)
x3 = tf.stack([x2, x2, x2, x2]) # (4,2,3)
x4 = tf.stack([x3, x3]) # (2,4,2,3)

`tf.constant` - produces constant tensors
`tf.Variable` - produces tensors that can be modified

In [12]:
# Tensors can be sliced
x = tf.constant([
    [3, 5, 7],
    [4, 6, 8]
])

# take ALL rows and only the first index column
y = x[:, 1]

In [13]:
# Tensors can be reshaped
x = tf.constant([
    [3, 5, 7],
    [4, 6, 8]
])

# reads input row by row and puts numbers in the output tensor
y = tf.reshape(x, [3, 2])

Variable constructor requires an initial value for variable which can be a tensor of any shape and type.
Initial value defines a shape and type for variable.
Type and shape of variable are fixed. Values could be changed using `.assign` call.

`tf.Variable` will typically hold model weights that need to be updated in a training loop

In [19]:
# x <- 2
x = tf.Variable(2.0, dtype=tf.float32, name='my_variable')
# x <- 45.8
x.assign(45.8)
# x <- x + 4
x.assign_add(4)
# x <- x - 3
x.assign_sub(3)

# w * x
w = tf.Variable([
    [1.],
    [2.]
])
x = tf.constant([
    [3., 4.]
])
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

TensorFlow can compute any derivative of a function with respect to any parameter.
- The computation is recorded with `GradientTape`
- The function is expressed with `TensorFlow operations only!`

# Computing loss gradient
GradientTape records operations for Automatic Differentiation

```python
def compute_gradients(X, Y, w0, w1):
    with tf.GradientTape() as tape: # record the computation with GradientTape when it is executed (not when it's defined!)
        loss = loss_mse(X, Y, w0, w1) # Specify the function (loss) as well as the parameters you want to take to the gradient with respect to ([w0, w1])
    return tape.gradient(loss, [w0, w1])

w0 = tf.Variable(0.0)
w1 = tf.Variable(0.0)

dw0, dw1 = compute_gradients(X, Y, w0, w1)
```